"use client";
import { useEffect, useState } from "react";

type Study={label:string;title:string;copy:string;image:string};
type Project={id:string;category:string;title:string;en:string;year:string;cover:string;intro:string;introEn:string;tags:string[];images:string[];role?:string;roleEn?:string;studies?:Study[]};

const projects:Project[]=[
 {id:"artscape",category:"UI / UX DESIGN",title:"艺境",en:"ARTSCAPE APP",year:"2026",cover:"/portfolio-new/artscape/home-01.jpg",intro:"连接情绪记录、艺术疗愈与内容探索的移动端产品，以低压力表达帮助用户建立温和的自我觉察。",introEn:"A gentle mobile experience connecting mood tracking, art-based healing and creative discovery.",role:"课题项目负责人｜我带领团队完成用户研究、竞品分析与需求定义，建立信息架构并拆分设计任务；主导体验策略与视觉规范，统筹线框、交互原型及高保真界面的完整落地。",roleEn:"Project Lead — Led research and product architecture, coordinated the team workflow, and directed the UX and visual system from wireframes to final delivery.",tags:["PROJECT LEAD","UX RESEARCH","PRODUCT STRATEGY","UI SYSTEM"],studies:[
  {label:"01 / PRE‑RESEARCH — 前期调研",title:"研究框架",copy:"从情绪表达、艺术疗愈和内容探索三条路径展开调研，将抽象的情绪需求转化为可执行的产品机会。",image:"/portfolio-new/artscape/research/page-1.jpg"},
  {label:"02 / INFORMATION HIERARCHY — 信息层级架构",title:"用户画像",copy:"聚焦希望低压力记录情绪、获得陪伴感，并通过艺术内容调节状态的年轻用户。",image:"/portfolio-new/artscape/research/page-2.jpg"},
  {label:"03 / INFORMATION FLOWCHART — 信息流程图",title:"体验路径",copy:"以记录—理解—舒缓—持续陪伴为核心链路，减少判断压力，让每一步都轻量且可退出。",image:"/portfolio-new/artscape/research/page-3.jpg"},
  {label:"04 / INTERFACE DESIGN — 界面设计",title:"设计回应",copy:"把研究结论落实为模块结构、视觉规范、IP角色和高保真体验，形成统一的情绪疗愈语言。",image:"/portfolio-new/artscape/research/page-4.jpg"}],images:["/portfolio-new/artscape/launch-01.jpg","/portfolio-new/artscape/home-01.jpg","/portfolio-new/artscape/home-04.jpg","/portfolio-new/artscape/content-04.jpg","/portfolio-new/artscape/content-10.jpg","/portfolio-new/artscape/content-16.jpg"]},
 {id:"mohu",category:"UI / UX DESIGN",title:"默护",en:"MOHU APP",year:"2026",cover:"/portfolio-new/mohu-case/logo.webp",intro:"面向阿尔茨海默症家庭的双端协同照护系统，以患者端被动辅助与家属端远程管理降低照护压力。",introEn:"A dual-sided care system for families living with Alzheimer’s, balancing patient dignity, safety and caregiver relief.",role:"课题项目负责人｜我带领团队从社会议题和真实照护情境出发，完成问题定义、家属调研、竞品量表与服务触点梳理；重点负责双端逻辑、关键任务流程和可用性判断，并协调内容策略、组件规范及成果汇报。",roleEn:"Project Lead — Framed the care challenge, directed family research and competitor evaluation, defined the dual-sided service flow, and coordinated content, components and final presentation.",tags:["PROJECT LEAD","SERVICE DESIGN","ACCESSIBILITY","DUAL-SIDED UX"],studies:[
  {label:"01 / PRE‑RESEARCH — 前期调研",title:"设计回应",copy:"从阿尔茨海默症家庭的真实照护情境出发，梳理患者与家属的双重需求、日常压力和关键服务触点。",image:"/portfolio-new/mohu-case/research-01.webp"},
  {label:"02 / DATA ANALYSIS – 数据分析",title:"设计回应",copy:"将问卷、访谈与竞品观察转化为需求优先级，明确安全监护、远程协同与低认知负担三条设计主线。",image:"/portfolio-new/mohu-case/analysis-01.webp"},
  {label:"03 / INTERFACE DESIGN — 界面设计",title:"设计回应",copy:"以清晰、友好和高容错为原则建立双端界面体系，让患者端更易使用，也让家属端更高效地完成照护管理。",image:"/portfolio-new/mohu-case/interface-01.webp"}],images:[]},
 {id:"luofu",category:"UI / UX DESIGN",title:"药隐罗浮·幻境寻踪",en:"HERBAL AR EXPERIENCE",year:"2026",cover:"/portfolio-new/luofu-ar/board-01.webp",intro:"以罗浮山冲虚古观草药文化为叙事核心，结合 AR 技术构建线上线下联动的沉浸式文化探索体验。",introEn:"An immersive cultural experience combining Luofu Mountain herbal heritage with AR-guided spatial storytelling.",tags:["AR EXPERIENCE","CULTURAL UX","IMMERSIVE DESIGN","VISUAL NARRATIVE"],images:Array.from({length:6},(_,i)=>`/portfolio-new/luofu-ar/board-${String(i+1).padStart(2,"0")}.webp`)},
 {id:"qinglan",category:"BRAND DESIGN",title:"青岚窑",en:"QINGLAN KILN",year:"2025",cover:"/portfolio-new/qinglan/board.webp",intro:"以宋瓷、汝窑天青色与传统建筑轮廓为核心建立品牌视觉系统。",introEn:"A visual identity rooted in Song ceramics, Ru-kiln celadon and traditional architecture.",tags:["BRAND STRATEGY","VISUAL IDENTITY","CULTURAL CREATIVE","FEASIBILITY"],images:["/portfolio-new/qinglan/board.webp",...Array.from({length:14},(_,i)=>`/portfolio-new/qinglan/identity-${String(i+1).padStart(2,"0")}.webp`)]},
 {id:"bamboo",category:"GRAPHIC DESIGN",title:"竹骨承闽韵",en:"FUJIAN UMBRELLA INFOGRAPHIC",year:"2025",cover:"/portfolio-new/graphic/bamboo-01.jpg",intro:"围绕福州油纸伞的结构、工艺与文化脉络展开的信息可视化设计。",introEn:"Information design translating the craft and cultural history of Fuzhou oil-paper umbrellas.",tags:["INFORMATION DESIGN","EDITORIAL","CULTURAL RESEARCH"],images:["/portfolio-new/graphic/bamboo-01.jpg","/portfolio-new/graphic/bamboo-02.jpg","/portfolio-new/graphic/bamboo-03.jpg","/portfolio-new/graphic/bamboo-04.jpg"]},
 {id:"taoyun",category:"GRAPHIC DESIGN",title:"桃韵联福",en:"PEACH RHYTHM",year:"2025",cover:"/portfolio-new/graphic/peach-01.jpg",intro:"将桃文化、祝福语义与现代图形语言结合，形成节庆系列视觉。",introEn:"A festive graphic series combining peach symbolism and contemporary composition.",tags:["POSTER","PATTERN","CULTURAL VISUAL"],images:["/portfolio-new/graphic/peach-01.jpg","/portfolio-new/graphic/peach-02.jpg","/portfolio-new/graphic/peach-03.jpg"]},
 {id:"graphic",category:"GRAPHIC DESIGN",title:"掌心的绿意",en:"SELECTED GRAPHIC WORKS",year:"2025—26",cover:"/portfolio-new/graphic/green-mountains.jpg",intro:"以生态议题与地方文化为线索的海报及插画实验。",introEn:"Poster and illustration experiments balancing ecological narratives and regional culture.",tags:["POSTER","ILLUSTRATION","VISUAL STORYTELLING"],images:["/portfolio-new/graphic/green-mountains.jpg"]},
 {id:"ocean-fish",category:"GRAPHIC DESIGN",title:"海洋鱼灯",en:"OCEAN FISH LANTERN",year:"2025—26",cover:"/portfolio-new/graphic/ocean-fish-lantern.jpg",intro:"以海洋生物与传统鱼灯为灵感，将高饱和色彩、民俗纹样和当代插画语言融合为充满生命力的视觉作品。",introEn:"A vibrant graphic work blending marine life, traditional fish-lantern culture and contemporary illustration.",tags:["POSTER","ILLUSTRATION","FOLK CULTURE"],images:["/portfolio-new/graphic/ocean-fish-lantern.jpg"]},
 {id:"kunlun",category:"CULTURAL CREATIVE",title:"烽火昆仑",en:"BEACON FIRE · KUNLUN PASS",year:"2025",cover:"/portfolio-new/cultural/kunlun-01.jpg",intro:"从昆仑关历史记忆出发，将地域叙事转化为可延展的文创视觉系统。",introEn:"A cultural creative system translating Kunlun Pass history into contemporary visual narrative.",tags:["CULTURAL CREATIVE","VISUAL SYSTEM","APPLICATION"],images:["/portfolio-new/cultural/kunlun-01.jpg","/portfolio-new/cultural/kunlun-02.jpg","/portfolio-new/cultural/kunlun-03.jpg"]}
];
const artscapeStageLabels=[
  "01 / PRE‑RESEARCH — 前期调研",
  "02 / INFORMATION HIERARCHY — 信息层级架构",
  "03 / INFORMATION FLOWCHART — 信息流程图",
  "04 / INTERFACE DESIGN — 界面设计",
];
const artscapeScreenGroups=[
  {title:"启动页",en:"LAUNCH SCREENS",items:Array.from({length:7},(_,i)=>`/portfolio-new/artscape/interface/launch-${String(i+1).padStart(2,"0")}.jpg`)},
  {title:"主页",en:"HOME SCREENS",items:Array.from({length:7},(_,i)=>`/portfolio-new/artscape/interface/home-${String(i+1).padStart(2,"0")}.jpg`)},
  {title:"内容页",en:"CONTENT SCREENS",items:Array.from({length:19},(_,i)=>`/portfolio-new/artscape/interface/content-${String(i+1).padStart(2,"0")}.jpg`)},
];

function ZoomableImage({src,alt}:{src:string;alt:string}){
 const[zoom,setZoom]=useState(1);
 return <div className="zoom-viewer"><div className="zoom-canvas"><img src={src} alt={alt} style={{transform:`scale(${zoom})`}}/></div><div className="zoom-controls" aria-label="图片缩放控制"><span>点击 ＋/－ 放大缩小 · RESET 复位</span><button onClick={()=>setZoom(v=>Math.max(.7,+(v-.2).toFixed(1)))} aria-label="缩小图片">－</button><b>{Math.round(zoom*100)}%</b><button onClick={()=>setZoom(v=>Math.min(2.4,+(v+.2).toFixed(1)))} aria-label="放大图片">＋</button><button onClick={()=>setZoom(1)}>RESET</button></div></div>
}
const mohuStageLabels=[
  "01 / PRE‑RESEARCH — 前期调研",
  "02 / DATA ANALYSIS – 数据分析",
  "03 / INTERFACE DESIGN — 界面设计",
];
const mohuResearch=Array.from({length:5},(_,i)=>`/portfolio-new/mohu-case/research-${String(i+1).padStart(2,"0")}.webp`);
const mohuAnalysis=Array.from({length:6},(_,i)=>`/portfolio-new/mohu-case/analysis-${String(i+1).padStart(2,"0")}.webp`);
const mohuScreenGroups=[
  {title:"启动与基础流程",en:"LAUNCH & ONBOARDING",start:1,count:5},
  {title:"患者端体验",en:"PATIENT EXPERIENCE",start:6,count:12},
  {title:"家属端管理",en:"FAMILY CARE",start:18,count:10},
  {title:"功能与状态页面",en:"FEATURES & STATES",start:28,count:13},
].map(group=>({...group,items:Array.from({length:group.count},(_,i)=>`/portfolio-new/mohu-case/interface-${String(group.start+i).padStart(2,"0")}.webp`)}));
const luofuLabels=[
 "01 / CONCEPT COVER — 概念封面",
 "02 / CULTURAL BACKGROUND — 文化背景",
 "03 / DESIGN RESEARCH — 设计调研",
 "04 / AR INTERACTION — AR 交互设计",
 "05 / EXPLORATION PATH — 探险路径",
 "06 / DESIGN OUTCOME — 设计成果",
];
function ImageLightbox({src,onClose}:{src:string;onClose:()=>void}){
 const[zoom,setZoom]=useState(1);
 return <div className="image-lightbox" role="dialog" aria-modal="true" aria-label="作品图片预览" onClick={onClose}><div className="lightbox-stage" onClick={e=>e.stopPropagation()}><img src={src} alt="作品大图预览" style={{transform:`scale(${zoom})`}}/></div><button className="lightbox-close" onClick={onClose}>CLOSE ×</button><div className="lightbox-tools" onClick={e=>e.stopPropagation()}><span>＋/－ 缩放 · 点击黑色区域关闭</span><button onClick={()=>setZoom(v=>Math.max(.5,+(v-.2).toFixed(1)))}>－</button><b>{Math.round(zoom*100)}%</b><button onClick={()=>setZoom(v=>Math.min(3,+(v+.2).toFixed(1)))}>＋</button><button onClick={()=>setZoom(1)}>RESET</button></div></div>
}
const groups=["UI / UX DESIGN","BRAND DESIGN","GRAPHIC DESIGN","CULTURAL CREATIVE"];
export default function Home(){
 const[menu,setMenu]=useState(false),[profile,setProfile]=useState(false),[active,setActive]=useState<Project|null>(null),[study,setStudy]=useState(0),[preview,setPreview]=useState<string|null>(null);
 useEffect(()=>{document.body.style.overflow=(menu||profile||active||preview)?"hidden":"";const fn=(e:KeyboardEvent)=>{if(e.key==="Escape"){if(preview){setPreview(null);return}setMenu(false);setProfile(false);setActive(null)}};window.addEventListener("keydown",fn);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",fn)}},[menu,profile,active,preview]);
 const open=(p:Project)=>{setStudy(0);setActive(p)};
 return <main>
  <header className="nav"><a className="monogram" href="#top">E.</a><div className="nav-note">VISUAL DESIGNER<br/>GUANGDONG · 2026</div><button className="menu-button" onClick={()=>setMenu(!menu)}><span>{menu?"CLOSE":"MENU"}</span><i/></button></header>
  <div className={`menu-panel ${menu?"open":""}`}><nav><a href="#work" onClick={()=>setMenu(false)}>Work</a><button onClick={()=>{setMenu(false);setProfile(true)}}>Profile</button><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav></div>
  <section className="hero" id="top"><div className="grain"/><div className="hero-meta"><span>PORTFOLIO</span><span>YIN YINGLIN</span><span>© 2026</span></div><h1>Eileen</h1><p className="intro">I’m Yin Yinglin, a Visual Communication Design student skilled in graphic, brand, cultural creative and UI design. I specialize in combining traditional Chinese style with modern visuals, and love telling warm stories through design.</p><a className="scroll-hint" href="#profile">ENTER PORTFOLIO <i/></a></section>
  <section className="profile-entry" id="profile"><button className="portrait-button" onClick={()=>setProfile(true)}><img src="/profile/portrait.jpg" alt="Yin Yinglin portrait"/><span><b>VIEW PROFILE</b><i>↗</i></span></button><div className="profile-copy"><em>01 — ABOUT / 关于我</em><h2>HELLO, I’M<br/><b>YIN YINGLIN.</b></h2><p>我是殷颖琳，视觉传达设计在读，深度关注UI 设计、品牌设计、平面设计与文创等，擅长国风融合现代视觉，手握10余项专业设计赛事奖项，精通各类设计软件包括运用AI制作交互游戏，兼顾设计逻辑与视觉美感，热爱用设计传递情绪与故事</p><button onClick={()=>setProfile(true)}>OPEN MY PROFILE <span>↗</span></button></div></section>
  <section className="work-index" id="work"><div className="work-heading"><em>02 — SELECTED WORK / 作品目录</em><h2>CHOOSE A<br/><b>STORY.</b></h2><p>点击项目封面进入完整内容<br/>CLICK A COVER TO OPEN THE CASE</p></div>{groups.map((g,i)=><div className="discipline" key={g}><div className="discipline-title"><span>0{i+1}</span><h3>{g}</h3><small>{projects.filter(p=>p.category===g).length.toString().padStart(2,"0")} PROJECTS</small></div><div className="project-grid">{projects.filter(p=>p.category===g).map(p=><button className={`project-card ${p.id}`} key={p.id} onClick={()=>open(p)}><div className="project-image"><img src={p.cover} alt={p.title}/><span>VIEW CASE <i>↗</i></span></div><div className="project-meta"><span>{p.year}</span><h4>{p.title}<small>{p.en}</small></h4><b>OPEN ↗</b></div>{p.id==="artscape"&&<p className="project-role-preview">我作为项目负责人，带队完成艺境 APP 设计。主打氛围感沉浸式用户体验，搭建柔和治愈的视觉体系。</p>}{p.id==="mohu"&&<p className="project-role-preview">我作为项目负责人，主导小组完成默护 APP 课程项目。以人文关怀为交互内核，打造适配目标群体的易用视觉架构。</p>}{p.id==="luofu"&&<p className="project-role-preview">以草药文化为叙事线索，将冲虚古观的空间探索、知识传播与 AR 互动整合为沉浸式体验。</p>}{p.id==="qinglan"&&<p className="project-role-preview">本人独立承担青岚窑全套设计工作，完成品牌定位、视觉规范、文创延展以及落地可行性探究。</p>}</button>)}</div></div>)}</section>
  <footer id="contact"><div>OPEN TO UI/UX · BRAND · GRAPHIC ROLES</div><h2>LET’S MAKE<br/><em>IDEAS VISIBLE.</em></h2><a href="https://mail.qq.com/" target="_blank" rel="noopener noreferrer" aria-label="打开 QQ 邮箱网页版">3255304062@QQ.COM ↗</a><small>EILEEN — YIN YINGLIN　/　VISUAL COMMUNICATION DESIGN · 2026</small></footer>
  <div className={`modal profile-modal ${profile?"show":""}`}><button className="close" onClick={()=>setProfile(false)}>CLOSE ×</button><div className="profile-modal-grid"><img src="/profile/portrait.jpg" alt="Yin Yinglin"/><div><em>PROFILE / 个人档案</em><h2>殷颖琳<small>YIN YINGLIN · EILEEN</small></h2><div className="cv-sections">
  <section><h3>基本信息<small>BASIC INFORMATION</small></h3><div className="basic-grid"><p><b>姓名</b>殷颖琳</p><p><b>专业</b>视觉传达设计</p><p><b>联系电话</b>13356419536</p><p><b>邮箱</b>3255304062@qq.com</p></div></section>
  <section><h3>教育经历<small>EDUCATION</small></h3><div className="education-head"><b>2023.9—2027.7</b><span>广东科技学院（本科）</span></div><ul><li>主修课程：版式设计、品牌设计、插画设计、UI/UX设计</li><li>软件课程：AI / PS / C4D / XD / PR / AE</li><li>综合测评：2 / 48</li></ul></section>
  <section><h3>专业荣誉<small>RECOGNITION</small></h3><div className="honor-list"><p><b>2023.09—2024.09</b><span>国家励志奖学金</span></p><p><b>2026.05</b><span>蓝桥杯插画设计三等奖</span></p><p><b>2026.05</b><span>米兰设计周二等奖</span></p><p><b>2026.06</b><span>IODA 绿水青山设计比赛银奖、铜奖</span></p></div></section>
  <section><h3>综合能力<small>CORE STRENGTHS</small></h3><ul><li>具备审美与色彩搭配能力，对国内外时尚潮流设计有持续关注。</li><li>学习能力强、责任心与执行力突出，能够快速按要求推进工作并协同团队。</li><li>设计思维活跃，重视创新，也愿意耐心尝试新事物。</li></ul></section>
</div><a href="mailto:3255304062@qq.com">CONTACT ME ↗</a></div></div></div>
  <div className={`modal project-modal ${active?"show":""}`}>{active&&<><div className="modal-bar"><span>EILEEN / {active.category}</span><button className="close" onClick={()=>setActive(null)}>CLOSE ×</button></div><article className="project-detail" onClick={e=>{const target=e.target as HTMLElement;if(target.tagName==="IMG")setPreview((target as HTMLImageElement).src)}}><header><em>CASE / {active.year}</em><h2>{active.title}<small>{active.en}</small></h2><div className="intro-grid"><p>{active.intro}</p><p>{active.introEn}</p></div><div className="tags">{active.tags.map(t=><span key={t}>{t}</span>)}</div></header>{active.role&&<section className="lead"><em>MY ROLE / 我的职责</em><h3>PROJECT<br/>LEAD.</h3><div><p>{active.role}</p><p>{active.roleEn}</p></div></section>}{active.studies&&<section className="research"><div className="research-copy"><em>DESIGN PROCESS / 设计过程</em><h3>{active.id==="artscape"||active.id==="mohu"?"设计回应":active.studies[study].title}</h3><p>{active.studies[study].copy}</p><div className="research-tabs">{active.studies.map((s,i)=><button className={i===study?"active":""} key={s.label} onClick={()=>{setStudy(i);if(active.id==="artscape"||active.id==="mohu")requestAnimationFrame(()=>document.getElementById(`${active.id}-stage-${i}`)?.scrollIntoView({behavior:"smooth",block:"start"}))}}>{s.label}</button>)}</div></div><div className="research-image"><img src={active.studies[study].image} alt={active.studies[study].title}/></div></section>}{active.id==="artscape"?<section className="artscape-content">
  <section id="artscape-stage-0" className="artscape-chapter pre-research"><h3>{artscapeStageLabels[0]}</h3><img src="/portfolio-new/artscape/research/page-1.jpg" alt="艺境前期调研"/></section>
  <section id="artscape-stage-1" className="artscape-chapter"><h3>{artscapeStageLabels[1]}</h3><ZoomableImage src="/portfolio-new/artscape/information-hierarchy.png" alt="艺境信息层级架构"/></section>
  <section id="artscape-stage-2" className="artscape-chapter"><h3>{artscapeStageLabels[2]}</h3><ZoomableImage src="/portfolio-new/artscape/information-flowchart.png" alt="艺境信息流程图"/></section>
  <section id="artscape-stage-3" className="artscape-chapter interface-chapter"><h3>{artscapeStageLabels[3]}</h3>{artscapeScreenGroups.map(group=><div className="screen-group" key={group.en}><header><b>{group.title}</b><span>{group.en}</span><small>{String(group.items.length).padStart(2,"0")} SCREENS</small></header><div className="screen-grid">{group.items.map((src,i)=><figure key={src}><span>{String(i+1).padStart(2,"0")}</span><img src={src} alt={`艺境${group.title} ${i+1}`}/></figure>)}</div></div>)}</section>
 </section>:active.id==="mohu"?<section className="artscape-content mohu-content">
  <section id="mohu-stage-0" className="artscape-chapter"><h3>{mohuStageLabels[0]}</h3><div className="case-board-grid">{mohuResearch.map((src,i)=><figure key={src}><span>{String(i+1).padStart(2,"0")}</span><img src={src} alt={`默护前期调研 ${i+1}`}/></figure>)}</div></section>
  <section id="mohu-stage-1" className="artscape-chapter"><h3>{mohuStageLabels[1]}</h3><div className="case-board-grid">{mohuAnalysis.map((src,i)=><figure key={src}><span>{String(i+1).padStart(2,"0")}</span><img src={src} alt={`默护数据分析 ${i+1}`}/></figure>)}</div></section>
  <section id="mohu-stage-2" className="artscape-chapter interface-chapter"><h3>{mohuStageLabels[2]}</h3>{mohuScreenGroups.map(group=><div className="screen-group" key={group.en}><header><b>{group.title}</b><span>{group.en}</span><small>{String(group.items.length).padStart(2,"0")} SCREENS</small></header><div className="screen-grid">{group.items.map((src,i)=><figure key={src}><span>{String(group.start+i).padStart(2,"0")}</span><img src={src} alt={`默护${group.title} ${i+1}`}/></figure>)}</div></div>)}</section>
 </section>:active.id==="luofu"?<section className="gallery luofu-gallery">{active.images.map((src,i)=><figure key={src}><span>{luofuLabels[i]}</span><img src={src} alt={`${active.title} ${i+1}`}/></figure>)}</section>:active.id==="qinglan"?<section className="gallery qinglan-gallery">{active.images.map((src,i)=><figure key={src}><span>{i===0?"01 / BRAND BOARD — 青岚窑品牌展板":`${String(i+1).padStart(2,"0")} / VISUAL IDENTITY — 品牌视觉`}</span><img src={src} alt={`${active.title} ${i+1}`}/></figure>)}</section>:active.id==="bamboo"?<section className="gallery bamboo-gallery">{active.images.map((src,i)=><figure key={src}><span>{String(i+1).padStart(2,"0")}</span><img src={src} alt={`${active.title} ${i+1}`}/></figure>)}</section>:active.id==="taoyun"?<section className="gallery taoyun-gallery">{active.images.map((src,i)=><figure key={src}><span>{String(i+1).padStart(2,"0")}</span><img src={src} alt={`${active.title} ${i+1}`}/></figure>)}</section>:active.id==="graphic"||active.id==="ocean-fish"?<section className="gallery graphic-gallery">{active.images.map((src,i)=><figure key={src}><span>{String(i+1).padStart(2,"0")}</span><img src={src} alt={`${active.title} ${i+1}`}/></figure>)}</section>:<section className="gallery">{active.images.map((src,i)=><figure key={src}><span>{String(i+1).padStart(2,"0")}</span><img src={src} alt={`${active.title} ${i+1}`}/></figure>)}</section>}<button className="next" onClick={()=>{const i=projects.findIndex(p=>p.id===active.id);open(projects[(i+1)%projects.length]);document.querySelector('.project-modal')?.scrollTo(0,0)}}><span>NEXT PROJECT</span><b>{projects[(projects.findIndex(p=>p.id===active.id)+1)%projects.length].title} ↗</b></button></article></>}</div>
  {preview&&<ImageLightbox key={preview} src={preview} onClose={()=>setPreview(null)}/>}
 </main>
}
