"use client";
import { useEffect, useState } from "react";

type Study={label:string;title:string;copy:string;image:string};
type Project={id:string;category:string;title:string;en:string;year:string;cover:string;intro:string;introEn:string;tags:string[];images:string[];role?:string;roleEn?:string;studies?:Study[]};

const projects:Project[]=[
 {id:"artscape",category:"UI / UX DESIGN",title:"艺境",en:"ARTSCAPE APP",year:"2026",cover:"/portfolio-new/artscape/home-01.jpg",intro:"连接情绪记录、艺术疗愈与内容探索的移动端产品，以低压力表达帮助用户建立温和的自我觉察。",introEn:"A gentle mobile experience connecting mood tracking, art-based healing and creative discovery.",role:"课题项目负责人｜我带领团队完成用户研究、竞品分析与需求定义，建立信息架构并拆分设计任务；主导体验策略与视觉规范，统筹线框、交互原型及高保真界面的完整落地。",roleEn:"Project Lead — Led research and product architecture, coordinated the team workflow, and directed the UX and visual system from wireframes to final delivery.",tags:["PROJECT LEAD","UX RESEARCH","PRODUCT STRATEGY","UI SYSTEM"],studies:[
  {label:"01 / RESEARCH",title:"研究框架",copy:"从情绪表达、艺术疗愈和内容探索三条路径展开调研，将抽象的情绪需求转化为可执行的产品机会。",image:"/portfolio-new/artscape/research/page-1.jpg"},
  {label:"02 / PERSONA",title:"用户画像",copy:"聚焦希望低压力记录情绪、获得陪伴感，并通过艺术内容调节状态的年轻用户。",image:"/portfolio-new/artscape/research/page-2.jpg"},
  {label:"03 / JOURNEY",title:"体验路径",copy:"以记录—理解—舒缓—持续陪伴为核心链路，减少判断压力，让每一步都轻量且可退出。",image:"/portfolio-new/artscape/research/page-3.jpg"},
  {label:"04 / SYSTEM",title:"设计回应",copy:"把研究结论落实为模块结构、视觉规范、IP角色和高保真体验，形成统一的情绪疗愈语言。",image:"/portfolio-new/artscape/research/page-4.jpg"}],images:["/portfolio-new/artscape/launch-01.jpg","/portfolio-new/artscape/home-01.jpg","/portfolio-new/artscape/home-04.jpg","/portfolio-new/artscape/content-04.jpg","/portfolio-new/artscape/content-10.jpg","/portfolio-new/artscape/content-16.jpg"]},
 {id:"mohu",category:"UI / UX DESIGN",title:"默护",en:"MOHU APP",year:"2026",cover:"/portfolio-new/mohu/screen-01.jpg",intro:"面向阿尔茨海默症家庭的双端协同照护系统，以患者端被动辅助与家属端远程管理降低照护压力。",introEn:"A dual-sided care system for families living with Alzheimer’s, balancing patient dignity, safety and caregiver relief.",role:"课题项目负责人｜我带领团队从社会议题和真实照护情境出发，完成问题定义、家属调研、竞品量表与服务触点梳理；重点负责双端逻辑、关键任务流程和可用性判断，并协调内容策略、组件规范及成果汇报。",roleEn:"Project Lead — Framed the care challenge, directed family research and competitor evaluation, defined the dual-sided service flow, and coordinated content, components and final presentation.",tags:["PROJECT LEAD","SERVICE DESIGN","ACCESSIBILITY","DUAL-SIDED UX"],studies:[
  {label:"01 / SURVEY",title:"家属调研",copy:"超半数家属每日照护投入超过3小时；对色彩友好、操作容错性高的监护工具接受度更高。",image:"/portfolio-new/mohu/research/survey.png"},
  {label:"02 / PERSONA",title:"双重用户",copy:"患者认知持续衰退、难以主动操作；家属长期担忧走失、服药与夜间安全，需要减少重复确认。",image:"/portfolio-new/mohu/research/persona.png"},
  {label:"03 / NEEDS",title:"需求优先级",copy:"紧急救助和定位为必备功能，体征监测为期望需求，语音陪伴与疾病科普作为体验增强。",image:"/portfolio-new/mohu/research/needs.png"},
  {label:"04 / JOURNEY",title:"照护旅程",copy:"从初期焦虑到长期使用，关键痛点集中于提醒不准、操作繁琐与适配不足。",image:"/portfolio-new/mohu/research/journey.png"},
  {label:"05 / BLUEPRINT",title:"服务蓝图",copy:"以家属管控加患者被动辅助为主线，串联定位、提醒、异常预警与后台支持。",image:"/portfolio-new/mohu/research/blueprint.png"}],images:["/portfolio-new/mohu/logo.png","/portfolio-new/mohu/screen-01.jpg","/portfolio-new/mohu/screen-04.jpg","/portfolio-new/mohu/screen-07.jpg","/portfolio-new/mohu/screen-10.jpg","/portfolio-new/mohu/screen-14.jpg"]},
 {id:"qinglan",category:"BRAND DESIGN",title:"青岚窑",en:"QINGLAN KILN",year:"2025",cover:"/portfolio/qinglan-cover.jpg",intro:"以宋瓷、汝窑天青色与传统建筑轮廓为核心建立品牌视觉系统。",introEn:"A visual identity rooted in Song ceramics, Ru-kiln celadon and traditional architecture.",tags:["BRAND STRATEGY","VISUAL IDENTITY","PACKAGING"],images:["/portfolio/qinglan-cover.jpg","/portfolio/qinglan-concept.jpg","/portfolio/qinglan-grid.jpg","/portfolio/qinglan-applications.jpg","/portfolio/qinglan-digital.jpg"]},
 {id:"bamboo",category:"GRAPHIC DESIGN",title:"竹骨承闽韵",en:"FUJIAN UMBRELLA INFOGRAPHIC",year:"2025",cover:"/portfolio-new/graphic/bamboo-01.jpg",intro:"围绕福州油纸伞的结构、工艺与文化脉络展开的信息可视化设计。",introEn:"Information design translating the craft and cultural history of Fuzhou oil-paper umbrellas.",tags:["INFORMATION DESIGN","EDITORIAL","CULTURAL RESEARCH"],images:["/portfolio-new/graphic/bamboo-01.jpg","/portfolio-new/graphic/bamboo-02.jpg","/portfolio-new/graphic/bamboo-03.jpg","/portfolio-new/graphic/bamboo-04.jpg"]},
 {id:"taoyun",category:"GRAPHIC DESIGN",title:"桃韵联福",en:"PEACH RHYTHM",year:"2025",cover:"/portfolio-new/graphic/peach-01.jpg",intro:"将桃文化、祝福语义与现代图形语言结合，形成节庆系列视觉。",introEn:"A festive graphic series combining peach symbolism and contemporary composition.",tags:["POSTER","PATTERN","CULTURAL VISUAL"],images:["/portfolio-new/graphic/peach-01.jpg","/portfolio-new/graphic/peach-02.jpg","/portfolio-new/graphic/peach-03.jpg"]},
 {id:"graphic",category:"GRAPHIC DESIGN",title:"平面作品选",en:"SELECTED GRAPHIC WORKS",year:"2025—26",cover:"/portfolio-new/graphic/green-mountains.jpg",intro:"以生态议题与地方文化为线索的海报及插画实验。",introEn:"Poster and illustration experiments balancing ecological narratives and regional culture.",tags:["POSTER","ILLUSTRATION","VISUAL STORYTELLING"],images:["/portfolio-new/graphic/green-mountains.jpg","/portfolio-new/graphic/ocean-fish-lantern.jpg"]},
 {id:"kunlun",category:"CULTURAL CREATIVE",title:"烽火昆仑",en:"BEACON FIRE · KUNLUN PASS",year:"2025",cover:"/portfolio-new/cultural/kunlun-01.jpg",intro:"从昆仑关历史记忆出发，将地域叙事转化为可延展的文创视觉系统。",introEn:"A cultural creative system translating Kunlun Pass history into contemporary visual narrative.",tags:["CULTURAL CREATIVE","VISUAL SYSTEM","APPLICATION"],images:["/portfolio-new/cultural/kunlun-01.jpg","/portfolio-new/cultural/kunlun-02.jpg","/portfolio-new/cultural/kunlun-03.jpg"]}
];
const groups=["UI / UX DESIGN","BRAND DESIGN","GRAPHIC DESIGN","CULTURAL CREATIVE"];
export default function Home(){
 const[menu,setMenu]=useState(false),[profile,setProfile]=useState(false),[active,setActive]=useState<Project|null>(null),[study,setStudy]=useState(0);
 useEffect(()=>{document.body.style.overflow=(menu||profile||active)?"hidden":"";const fn=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenu(false);setProfile(false);setActive(null)}};window.addEventListener("keydown",fn);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",fn)}},[menu,profile,active]);
 const open=(p:Project)=>{setStudy(0);setActive(p)};
 return <main>
  <header className="nav"><a className="monogram" href="#top">E.</a><div className="nav-note">VISUAL DESIGNER<br/>GUANGDONG · 2026</div><button className="menu-button" onClick={()=>setMenu(!menu)}><span>{menu?"CLOSE":"MENU"}</span><i/></button></header>
  <div className={`menu-panel ${menu?"open":""}`}><nav><a href="#work" onClick={()=>setMenu(false)}>Work</a><button onClick={()=>{setMenu(false);setProfile(true)}}>Profile</button><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav></div>
  <section className="hero" id="top"><div className="grain"/><div className="hero-meta"><span>PORTFOLIO</span><span>YIN YINGLIN</span><span>© 2026</span></div><h1>Eileen</h1><p className="intro">I’m Yin Yinglin, a Visual Communication Design student skilled in graphic, brand, cultural creative and UI design. I specialize in combining traditional Chinese style with modern visuals, and love telling warm stories through design.</p><a className="scroll-hint" href="#profile">ENTER PORTFOLIO <i/></a></section>
  <section className="profile-entry" id="profile"><button className="portrait-button" onClick={()=>setProfile(true)}><img src="/profile/portrait.jpg" alt="Yin Yinglin portrait"/><span><b>VIEW PROFILE</b><i>↗</i></span></button><div className="profile-copy"><em>01 — ABOUT / 关于我</em><h2>HELLO, I’M<br/><b>YIN YINGLIN.</b></h2><p>我是殷颖琳，视觉传达设计在读，深度关注UI 设计、品牌设计、平面设计与文创等，擅长国风融合现代视觉，手握10余项专业设计赛事奖项，精通各类设计软件包括运用AI制作交互游戏，兼顾设计逻辑与视觉美感，热爱用设计传递情绪与故事</p><button onClick={()=>setProfile(true)}>OPEN MY PROFILE <span>↗</span></button></div></section>
  <section className="work-index" id="work"><div className="work-heading"><em>02 — SELECTED WORK / 作品目录</em><h2>CHOOSE A<br/><b>STORY.</b></h2><p>点击项目封面进入完整内容<br/>CLICK A COVER TO OPEN THE CASE</p></div>{groups.map((g,i)=><div className="discipline" key={g}><div className="discipline-title"><span>0{i+1}</span><h3>{g}</h3><small>{projects.filter(p=>p.category===g).length.toString().padStart(2,"0")} PROJECTS</small></div><div className="project-grid">{projects.filter(p=>p.category===g).map(p=><button className="project-card" key={p.id} onClick={()=>open(p)}><div className="project-image"><img src={p.cover} alt={p.title}/><span>VIEW CASE <i>↗</i></span></div><div className="project-meta"><span>{p.year}</span><h4>{p.title}<small>{p.en}</small></h4><b>OPEN ↗</b></div></button>)}</div></div>)}</section>
  <section className="recognition"><em>03 — RECOGNITION / 荣誉</em><div className="award-list"><div><span>2023—2024</span><p>国家励志奖学金<small>National Encouragement Scholarship</small></p></div><div><span>2026.05</span><p>蓝桥杯插画设计三等奖<small>Lanqiao Cup — Third Prize</small></p></div><div><span>2026.05</span><p>米兰设计周二等奖<small>Milan Design Week — Second Prize</small></p></div><div><span>2026.06</span><p>ICDA 绿水青山设计比赛银奖、铜奖<small>ICDA — Silver & Bronze Awards</small></p></div></div></section>
  <footer id="contact"><div>OPEN TO UI/UX · BRAND · GRAPHIC ROLES</div><h2>LET’S MAKE<br/><em>IDEAS VISIBLE.</em></h2><a href="mailto:3255304062@qq.com">3255304062@QQ.COM ↗</a><small>EILEEN — YIN YINGLIN　/　VISUAL COMMUNICATION DESIGN · 2026</small></footer>
  <div className={`modal profile-modal ${profile?"show":""}`}><button className="close" onClick={()=>setProfile(false)}>CLOSE ×</button><div className="profile-modal-grid"><img src="/profile/portrait.jpg" alt="Yin Yinglin"/><div><em>PROFILE / 个人档案</em><h2>殷颖琳<small>YIN YINGLIN · EILEEN</small></h2><p>视觉传达设计本科在读，专注 UI/UX、品牌与平面设计。我擅长把复杂信息整理为清晰的视觉结构，也喜欢从传统文化中提取当代设计语言，用理性的方法讲有温度的故事。</p><p className="en">Visual Communication Design student focused on UI/UX, brand and graphic design. I translate complex information and cultural narratives into clear, contemporary visual systems.</p><div className="stats"><div><b>2023—2027</b><span>广东科技学院<br/>视觉传达设计</span></div><div><b>2 / 48</b><span>专业综合测评排名</span></div><div><b>AI · PS · C4D</b><span>XD · PR · AE</span></div><div><b>UI/UX · BRAND</b><span>GRAPHIC DESIGN</span></div></div><a href="mailto:3255304062@qq.com">CONTACT ME ↗</a></div></div></div>
  <div className={`modal project-modal ${active?"show":""}`}>{active&&<><div className="modal-bar"><span>EILEEN / {active.category}</span><button className="close" onClick={()=>setActive(null)}>CLOSE ×</button></div><article className="project-detail"><header><em>CASE / {active.year}</em><h2>{active.title}<small>{active.en}</small></h2><div className="intro-grid"><p>{active.intro}</p><p>{active.introEn}</p></div><div className="tags">{active.tags.map(t=><span key={t}>{t}</span>)}</div></header>{active.role&&<section className="lead"><em>MY ROLE / 我的职责</em><h3>PROJECT<br/>LEAD.</h3><div><p>{active.role}</p><p>{active.roleEn}</p></div></section>}{active.studies&&<section className="research"><div className="research-copy"><em>RESEARCH / 调研过程</em><h3>{active.studies[study].title}</h3><p>{active.studies[study].copy}</p><div className="research-tabs">{active.studies.map((s,i)=><button className={i===study?"active":""} key={s.label} onClick={()=>setStudy(i)}>{s.label}</button>)}</div></div><div className="research-image"><img src={active.studies[study].image} alt={active.studies[study].title}/></div></section>}<section className="gallery">{active.images.map((src,i)=><figure key={src}><span>{String(i+1).padStart(2,"0")}</span><img src={src} alt={`${active.title} ${i+1}`}/></figure>)}</section><button className="next" onClick={()=>{const i=projects.findIndex(p=>p.id===active.id);open(projects[(i+1)%projects.length]);document.querySelector('.project-modal')?.scrollTo(0,0)}}><span>NEXT PROJECT</span><b>{projects[(projects.findIndex(p=>p.id===active.id)+1)%projects.length].title} ↗</b></button></article></>}</div>
 </main>
}
